include:
  - board: le_chiff_ble
    artifact-name: schiffer_bleu
    keyboard_name: "schiffer bleu"

  - board: le_chiff_ble
    artifact-name: schiffer_pink
    keyboard_name: "schiffer pink"

  - board: le_chiff_ble
    artifact-name: schiffer_gelb
    keyboard_name: "schiffer gelb"
